### ISSUE TITLE
failed run

### ISSUE THREAD

**Issue by mzupan** [autofitcloud/isitfit#4]
Failing. Havent looked too much into this

```
$ isitfit
Is it fit?
Initializing
Fetching history...
Found 99 EC2 instances
Cloudtrail page 1: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/isitfit", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/isitfit/cli.py", line 51, in cli
    mm.get_ifi()
  File "/usr/local/lib/python3.7/site-packages/isitfit/mainManager.py", line 65, in get_ifi
    self.cloudtrail_manager.init_data(self.ec2_resource.instances.all(), n_ec2)
  File "/usr/local/lib/python3.7/site-packages/isitfit/cloudtrail_ec2type.py", line 18, in init_data
    self.df_cloudtrail = self._fetch()
  File "/usr/local/lib/python3.7/site-packages/isitfit/cloudtrail_ec2type.py", line 33, in _fetch
    df = cloudtrail_manager.ec2_typeChanges()
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 167, in ec2_typeChanges
    r_run = man2_run.handleIterator(iterator_run)
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 87, in handleIterator
    result = self._handleEventAny(event)
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 96, in _handleEventAny
    return self._handleEventRun(event)
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 108, in _handleEventRun
    instanceId = [x for x in event['Resources'] if x['ResourceType']=='AWS::EC2::Instance'][0]['ResourceName']
IndexError: list index out of range
```

**Comment by shadiakiki1986** [comment]
Could you run "isitfit --debug" and share the output?

**Comment by mzupan** [comment]
```
$ isitfit --debug
Is it fit?
Initializing
Metrics start..end: 2019-06-15 10:56:32.885935+00:00 .. 2019-09-13 10:56:32.885935+00:00
Fetching history...
Found 91 EC2 instances
Downloading ec2 catalog
Downloading cloudtrail data
Cloudtrail page 1: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/isitfit", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/isitfit/cli.py", line 51, in cli
    mm.get_ifi()
  File "/usr/local/lib/python3.7/site-packages/isitfit/mainManager.py", line 65, in get_ifi
    self.cloudtrail_manager.init_data(self.ec2_resource.instances.all(), n_ec2)
  File "/usr/local/lib/python3.7/site-packages/isitfit/cloudtrail_ec2type.py", line 18, in init_data
    self.df_cloudtrail = self._fetch()
  File "/usr/local/lib/python3.7/site-packages/isitfit/cloudtrail_ec2type.py", line 33, in _fetch
    df = cloudtrail_manager.ec2_typeChanges()
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 167, in ec2_typeChanges
    r_run = man2_run.handleIterator(iterator_run)
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 87, in handleIterator
    result = self._handleEventAny(event)
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 96, in _handleEventAny
    return self._handleEventRun(event)
  File "/usr/local/lib/python3.7/site-packages/isitfit/pull_cloudtrail_lookupEvents.py", line 108, in _handleEventRun
    instanceId = [x for x in event['Resources'] if x['ResourceType']=='AWS::EC2::Instance'][0]['ResourceName']
IndexError: list index out of range
```

**Comment by shadiakiki1986** [comment]
I just released 0.2.5. You could upgrade with `pip3 install --upgrade isitfit`

This upgrade checks more thoroughly for missing keys, and I added some more informative output to the `--debug` flag. It would be great if this works for you now, and if you could still share `isitfit --debug` even if it's running, just so that I could see the issue further.

**Comment by shadiakiki1986** [comment]
Hello, just checking in to see if the upgrade fixed the issue for you.

**Comment by shadiakiki1986** [comment]
Closing due to inactivity
